services:
  postgres:
    image: postgres:15
    container_name: electroplan-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: electroplan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: